In [3]:
import numpy as np

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [7]:
a < 0

array([False, False, False, False, False, False, False, False, False,
       False])

In [8]:
np.any(a>5)

True

In [9]:
np.all(a<0)

False

In [14]:
test_a = np.array([1,3,0],float)
test_a

array([1., 3., 0.])

In [15]:
test_b = np.array([5,2,1],float)
test_b

array([5., 2., 1.])

In [16]:
test_a + test_b

array([6., 5., 1.])

In [18]:
test_a * test_b

array([5., 6., 0.])

In [19]:
test_a > test_b

array([False,  True, False])

In [20]:
test_a == test_b

array([False, False, False])

In [21]:
np.any(test_a > test_b)

True

In [22]:
np.all(test_a > test_b)

False

In [ ]:
# boolean indexingt

In [23]:
test_array = np.array([1,4,0,2,3,8,9,7])
test_array

array([1, 4, 0, 2, 3, 8, 9, 7])

In [24]:
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [25]:
test_array[test_array>3]

array([4, 8, 9, 7])

In [26]:
names = np.array(['bon','kim','jim','park'])
names

array(['bon', 'kim', 'jim', 'park'], dtype='<U4')

In [ ]:
#boolean indexing을 통해서 'kim'을 출력하시오

In [30]:
a = names == 'kim'
a

array([False,  True, False, False])

In [31]:
names[a]

array(['kim'], dtype='<U4')

In [ ]:
#names에서 'kim'이 아닌 사람을 boolean indexing 출력

In [33]:
a = names != 'kim'
a

array([ True, False,  True,  True])

In [34]:
names[a]

array(['bon', 'jim', 'park'], dtype='<U4')

In [36]:
randarr = np.random.rand(7,4)
randarr

array([[0.23712328, 0.66565085, 0.03893334, 0.44912658],
       [0.33685442, 0.13049015, 0.62299763, 0.34477561],
       [0.22139515, 0.99254386, 0.77974871, 0.86280765],
       [0.45299556, 0.30060394, 0.28121887, 0.07528916],
       [0.91644843, 0.89738299, 0.25739627, 0.26121352],
       [0.57211371, 0.42367087, 0.92758985, 0.14333151],
       [0.18725403, 0.00315572, 0.48754555, 0.9024741 ]])

In [41]:
randarr = np.random.randn(7,4)
randarr

array([[ 0.31480559, -0.3107015 ,  2.21144609,  0.57315079],
       [ 0.62074632, -0.07921747, -0.9326132 ,  0.35660494],
       [-1.31311774,  0.17368988,  0.78822059,  0.93400183],
       [ 1.58208342, -0.43415617, -0.31661879, -0.69075708],
       [ 1.29386493,  1.01414826, -1.05778947, -0.19974826],
       [ 0.85941047,  0.12569713, -0.49947651,  0.31967352],
       [-1.21439509,  0.6693731 , -0.21948605, -0.90571081]])

In [42]:
a = randarr > 0
a

array([[ True, False,  True,  True],
       [ True, False, False,  True],
       [False,  True,  True,  True],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True, False,  True],
       [False,  True, False, False]])

In [43]:
randarr[a]

array([0.31480559, 2.21144609, 0.57315079, 0.62074632, 0.35660494,
       0.17368988, 0.78822059, 0.93400183, 1.58208342, 1.29386493,
       1.01414826, 0.85941047, 0.12569713, 0.31967352, 0.6693731 ])

In [44]:
# 1에서부터 100까지 정수에서 20보다 크고 70보다 작은 3의 배수를 출력

In [58]:
a = np.arange(1,101)

In [59]:
a > 20

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [62]:
a < 70

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [68]:
a % 3 ==0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False])

In [66]:
b = (a > 20)&(a<70)&(a%3==0)

In [67]:
a[b]

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69])

In [69]:
arr = np.array([2,3,4,5,4,7,6,8,6])
arr

array([2, 3, 4, 5, 4, 7, 6, 8, 6])

In [70]:
arr[5]

7

In [73]:
arr[[1,5,6]]

array([3, 7, 6])

In [74]:
arr[[2,3,4]]

array([4, 5, 4])