In [1]:
import numpy as np

In [2]:
L = [1,4,5]

In [3]:
np.array(L)

array([1, 4, 5])

In [7]:
arr = np.array(L,float)
arr

array([1., 4., 5.])

In [10]:
arr[2]

5.0

In [ ]:
#numpy 모두 동일한 데이터 타입의 원소를 갖는다

In [11]:
L = [1,4,7,'8']
np.array(L)

array(['1', '4', '7', '8'], dtype='<U11')

In [12]:
arr = np.array(L)
arr

array(['1', '4', '7', '8'], dtype='<U11')

In [13]:
arr.ndim #1차원 : vector, 2차원 : matrix, 3차원 : tensor

1

In [14]:
arr.shape #원소 하나의 1차원 vector

(4,)

In [ ]:
# matrix (2차원:행,열)

In [15]:
L = [[1,2,3,4],[4,3,3,5],[6,7,8,5]]

In [18]:
mat = np.array(L)
mat

array([[1, 2, 3, 4],
       [4, 3, 3, 5],
       [6, 7, 8, 5]])

In [20]:
mat.shape

(3, 4)

In [21]:
mat.ndim

2

In [ ]:
# tensor (3차원)

In [22]:
T = [[[1,2,3,4],[4,3,3,5],[6,7,8,5]],
[[1,2,3,4],[4,3,3,5],[6,7,8,5]],
[[1,2,3,4],[4,3,3,5],[6,7,8,5]]]

In [24]:
tensor = np.array(T)
tensor

array([[[1, 2, 3, 4],
        [4, 3, 3, 5],
        [6, 7, 8, 5]],

       [[1, 2, 3, 4],
        [4, 3, 3, 5],
        [6, 7, 8, 5]],

       [[1, 2, 3, 4],
        [4, 3, 3, 5],
        [6, 7, 8, 5]]])

In [25]:
tensor.shape

(3, 3, 4)

In [28]:
#reshape

In [29]:
L = [[1,3,5,6],[7,8,5,4]]
mat = np.array(L)

In [30]:
mat.shape

(2, 4)

In [31]:
mat.ndim

2

In [32]:
mat.size #원소개수

8

In [34]:
mat.reshape(8)

array([1, 3, 5, 6, 7, 8, 5, 4])

In [36]:
mat.reshape(4,2)

array([[1, 3],
       [5, 6],
       [7, 8],
       [5, 4]])

In [37]:
mat.reshape(2,2,2)

array([[[1, 3],
        [5, 6]],

       [[7, 8],
        [5, 4]]])

In [ ]:
#mat.reshape(3,4) #reshape을 하되,size가 유지되는 reshape

In [40]:
L = [[1,2,3,4],[5,5,6,5],[8,6,4,6]]

In [42]:
mat = np.array(L)
mat

array([[1, 2, 3, 4],
       [5, 5, 6, 5],
       [8, 6, 4, 6]])

In [44]:
mat.size

12

In [45]:
mat.ndim

2

In [47]:
mat.reshape(2,6)

array([[1, 2, 3, 4, 5, 5],
       [6, 5, 8, 6, 4, 6]])

In [48]:
mat.reshape(1,12)

array([[1, 2, 3, 4, 5, 5, 6, 5, 8, 6, 4, 6]])

In [53]:
mat.reshape(-1,6) #행은 상관없고 열만 6개로 맞춰라...

array([[1, 2, 3, 4, 5, 5],
       [6, 5, 8, 6, 4, 6]])

In [54]:
mat

array([[1, 2, 3, 4],
       [5, 5, 6, 5],
       [8, 6, 4, 6]])

In [58]:
mat[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [59]:
mat[1:,2:]

array([[6, 5],
       [4, 6]])

In [61]:
mat[:2,1:4:2]

array([[2, 4],
       [5, 5]])

In [63]:
mat[1,1:3]

array([5, 6])

In [ ]:
#mat[행,열]
#행 - 가로축 row
#열 - 세로축 columns

In [65]:
mat[2,3] = 100  # or mat[-1,-1]

In [66]:
mat

array([[  1,   2,   3,   4],
       [  5,   5,   6,   5],
       [  8,   6,   4, 100]])

In [67]:
L = [1,3,4,5,6]
sum(L)

19

In [68]:
min(L)

1

In [69]:
max(L)

6

In [70]:
sum(L)/len(L) #mean

3.8

In [73]:
sum(mat)

array([ 14,  13,  13, 109])

In [75]:
mat.sum(axis=1) #가로축 axis = 1 #세로축 axis = 0 

array([ 10,  21, 118])

In [76]:
mat.max(axis=0)

array([  8,   6,   6, 100])

In [77]:
mat.max(axis=1)

array([  4,   6, 100])

In [78]:
# std : 표준편차

mat.std(axis=1)

array([ 1.11803399,  0.4330127 , 40.72775466])

In [79]:
# var: 분산

mat.var(axis=0)

array([8.22222222e+00, 2.88888889e+00, 1.55555556e+00, 2.02688889e+03])

In [80]:
# np.sqrt : 제곱근

np.sqrt(mat)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.23606798,  2.44948974,  2.23606798],
       [ 2.82842712,  2.44948974,  2.        , 10.        ]])

In [ ]:
#python에서 연속값을 생성하는 함수

In [81]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [82]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [ ]:
#numpy에도 연속값을 생성하는 함수..

In [84]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [86]:
#range(1,10,0.5) #pythono에서는 range가 간격이 정수만 가능

TypeError: 'float' object cannot be interpreted as an integer

In [88]:
np.arange(1,10,0.1) #numpy에서는 range가 간격이 소수도 가능 - 정교한 수치데이터 생성...

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [89]:
#numpy의 연산은 element wise operation - 동일한 인덱스 요소간의 연산..

In [90]:
mat1 = np.array([[1,2,3,4],[4,5,6,7]])
mat2 = np.array([[7,8,5,4],[4,3,2,1]])

In [91]:
mat1

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [92]:
mat2

array([[7, 8, 5, 4],
       [4, 3, 2, 1]])

In [93]:
mat1 + mat2

array([[ 8, 10,  8,  8],
       [ 8,  8,  8,  8]])

In [94]:
vec1 = np.array([5,6,7,8])
vec1

array([5, 6, 7, 8])

In [95]:
mat1 + vec1 #broadcasting operation : shape이 다른 array간에 shape을 일치시켜서 연산하도록 ...

array([[ 6,  8, 10, 12],
       [ 9, 11, 13, 15]])

In [96]:
mat1 * 2

array([[ 2,  4,  6,  8],
       [ 8, 10, 12, 14]])

In [97]:
mat1 - mat2

array([[-6, -6, -2,  0],
       [ 0,  2,  4,  6]])