In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# numpy

In [4]:
# 1
L = [1,4,5,8]
np.array(L)

array([1, 4, 5, 8])

In [8]:
# 2
arr = np.arange(8)
arr = arr.reshape(2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [9]:
# 3
arr.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [10]:
# 4 
arr.sum(axis=1)

array([ 6, 22])

In [11]:
# 5
arr = np.arange(1, 21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
# 6
arr > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [13]:
arr % 3 == 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [14]:
arr[(arr > 10) & (arr % 3 == 0)]

array([12, 15, 18])

In [15]:
# 7
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
arr1 = arr.reshape(4,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
# 8.

arr1[:,1]

array([ 2,  7, 12, 17])

In [21]:
# 9
arr1[:2, 2:4]

array([[3, 4],
       [8, 9]])

In [22]:
arr1[:2, [2,3]]

array([[3, 4],
       [8, 9]])

In [23]:
# 10

In [25]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
arr1[1:3, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [30]:
# arr1[[1,2], [1,2,3]]

In [31]:
# 11

In [35]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
arr1.max(axis=0)

array([16, 17, 18, 19, 20])

### pandas

In [34]:
# 10

In [37]:
ls = [1,2,3,4,5]
s = pd.Series(ls)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# 11

In [40]:
s[2]

3

In [ ]:
# 12

In [41]:
s[[1,2]]

1    2
2    3
dtype: int64

In [42]:
s[2:]

2    3
3    4
4    5
dtype: int64

In [ ]:
# 13

In [44]:
s[2] =10
s

0     1
1     2
2    10
3     4
4     5
dtype: int64

In [45]:
# 14

s > 3

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [46]:
s[s>3]

2    10
3     4
4     5
dtype: int64

In [47]:
# 15

In [51]:
s.index.tolist()

[0, 1, 2, 3, 4]

In [52]:
# 16

In [53]:
s.values

array([ 1,  2, 10,  4,  5], dtype=int64)

In [ ]:
# 17

In [210]:
raw_data= {'first_name': ['jason',np.nan, 'tina','jake','amy'],
          'last_name': ['miller', np.nan, 'all','miler','coozer'],
          'age': [42, np.nan, 36, 24, 73],
          'sex': ['m', np.nan, 'f','m','f'],
          'pretestscore': [4, np.nan, np.nan, 2, 3],
          'posttestscore': [25, np.nan, np.nan, 62, 70],
          'addr': ['seoul','Incheon', 'Pusan', 'Gwangju', 'Daejeoun']}

df = pd.DataFrame(raw_data)
df

first_name last_name   age  sex  pretestscore  posttestscore      addr
0      jason    miller  42.0    m           4.0           25.0     seoul
1        NaN       NaN   NaN  NaN           NaN            NaN   Incheon
2       tina       all  36.0    f           NaN            NaN     Pusan
3       jake     miler  24.0    m           2.0           62.0   Gwangju
4        amy    coozer  73.0    f           3.0           70.0  Daejeoun

In [211]:
# 18

In [212]:
df.columns

Index(['first_name', 'last_name', 'age', 'sex', 'pretestscore',
       'posttestscore', 'addr'],
      dtype='object')

In [213]:
# 19

In [214]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [215]:
# 20 
df['sex']

0      m
1    NaN
2      f
3      m
4      f
Name: sex, dtype: object

In [216]:
df.sex

0      m
1    NaN
2      f
3      m
4      f
Name: sex, dtype: object

In [217]:
# 21

In [218]:
df[['sex', 'posttestscore']]

sex  posttestscore
0    m           25.0
1  NaN            NaN
2    f            NaN
3    m           62.0
4    f           70.0

In [219]:
# 22

In [220]:
df[['sex', 'pretestscore', 'posttestscore']]

sex  pretestscore  posttestscore
0    m           4.0           25.0
1  NaN           NaN            NaN
2    f           NaN            NaN
3    m           2.0           62.0
4    f           3.0           70.0

In [221]:
df.loc[:, 'sex': 'posttestscore']

sex  pretestscore  posttestscore
0    m           4.0           25.0
1  NaN           NaN            NaN
2    f           NaN            NaN
3    m           2.0           62.0
4    f           3.0           70.0

In [222]:
df.iloc[:, 3:6]

sex  pretestscore  posttestscore
0    m           4.0           25.0
1  NaN           NaN            NaN
2    f           NaN            NaN
3    m           2.0           62.0
4    f           3.0           70.0

In [223]:
# 23

In [224]:
df.index = ['a','b','c','d','e']
df

first_name last_name   age  sex  pretestscore  posttestscore      addr
a      jason    miller  42.0    m           4.0           25.0     seoul
b        NaN       NaN   NaN  NaN           NaN            NaN   Incheon
c       tina       all  36.0    f           NaN            NaN     Pusan
d       jake     miler  24.0    m           2.0           62.0   Gwangju
e        amy    coozer  73.0    f           3.0           70.0  Daejeoun

In [225]:
# 24

In [226]:
df.loc['a']

first_name        jason
last_name        miller
age                  42
sex                   m
pretestscore          4
posttestscore        25
addr              seoul
Name: a, dtype: object

In [227]:
df.iloc[0]

first_name        jason
last_name        miller
age                  42
sex                   m
pretestscore          4
posttestscore        25
addr              seoul
Name: a, dtype: object

In [228]:
# 25

In [229]:
df.loc[['a','b','c']]

first_name last_name   age  sex  pretestscore  posttestscore     addr
a      jason    miller  42.0    m           4.0           25.0    seoul
b        NaN       NaN   NaN  NaN           NaN            NaN  Incheon
c       tina       all  36.0    f           NaN            NaN    Pusan

In [230]:
df.iloc[[0,1,2]]

first_name last_name   age  sex  pretestscore  posttestscore     addr
a      jason    miller  42.0    m           4.0           25.0    seoul
b        NaN       NaN   NaN  NaN           NaN            NaN  Incheon
c       tina       all  36.0    f           NaN            NaN    Pusan

In [231]:
df.loc['a': 'c']

first_name last_name   age  sex  pretestscore  posttestscore     addr
a      jason    miller  42.0    m           4.0           25.0    seoul
b        NaN       NaN   NaN  NaN           NaN            NaN  Incheon
c       tina       all  36.0    f           NaN            NaN    Pusan

In [232]:
# 26

In [233]:
df.iloc[:2]

first_name last_name   age  sex  pretestscore  posttestscore     addr
a      jason    miller  42.0    m           4.0           25.0    seoul
b        NaN       NaN   NaN  NaN           NaN            NaN  Incheon

In [234]:
# 27

In [235]:
df[df.age > 40].first_name

a    jason
e      amy
Name: first_name, dtype: object

In [236]:
# 28

In [237]:
df[df.first_name == 'jason'].pretestscore

a    4.0
Name: pretestscore, dtype: float64

In [238]:
# 29

In [239]:
df[df.sex == 'f'].age.mean()

54.5

In [240]:
df.groupby('sex')['age'].mean().loc['f']

54.5

In [241]:
# 30

In [242]:
max_age = df.age.max()
df[df.age == max_age]['first_name']

e    amy
Name: first_name, dtype: object

In [243]:
# 31

df['age'] = [42,25,78,41,23]
df

first_name last_name  age  sex  pretestscore  posttestscore      addr
a      jason    miller   42    m           4.0           25.0     seoul
b        NaN       NaN   25  NaN           NaN            NaN   Incheon
c       tina       all   78    f           NaN            NaN     Pusan
d       jake     miler   41    m           2.0           62.0   Gwangju
e        amy    coozer   23    f           3.0           70.0  Daejeoun

In [244]:
# 32

df.columns = ['fn','ln','age','sex','prets','postts','addr']
# df.rename(columns = {'first_name':'fn', 'last_name':'ln', 'pretestscore':'prets', \
#                     'posttestscore':'postts', 'address':'addr'})
df

fn      ln  age  sex  prets  postts      addr
a  jason  miller   42    m    4.0    25.0     seoul
b    NaN     NaN   25  NaN    NaN     NaN   Incheon
c   tina     all   78    f    NaN     NaN     Pusan
d   jake   miler   41    m    2.0    62.0   Gwangju
e    amy  coozer   23    f    3.0    70.0  Daejeoun

In [245]:
# 33

In [246]:
df.drop('age', axis=1)

fn      ln  sex  prets  postts      addr
a  jason  miller    m    4.0    25.0     seoul
b    NaN     NaN  NaN    NaN     NaN   Incheon
c   tina     all    f    NaN     NaN     Pusan
d   jake   miler    m    2.0    62.0   Gwangju
e    amy  coozer    f    3.0    70.0  Daejeoun

In [247]:
# 34

In [248]:
df.drop('b', axis=0)

fn      ln  age sex  prets  postts      addr
a  jason  miller   42   m    4.0    25.0     seoul
c   tina     all   78   f    NaN     NaN     Pusan
d   jake   miler   41   m    2.0    62.0   Gwangju
e    amy  coozer   23   f    3.0    70.0  Daejeoun

In [249]:
# 35

In [250]:
df.isnull()

fn     ln    age    sex  prets  postts   addr
a  False  False  False  False  False   False  False
b   True   True  False   True   True    True  False
c  False  False  False  False   True    True  False
d  False  False  False  False  False   False  False
e  False  False  False  False  False   False  False

In [251]:
df.isnull().sum(axis=1)

a    0
b    5
c    2
d    0
e    0
dtype: int64

In [252]:
# 36

In [253]:
df

fn      ln  age  sex  prets  postts      addr
a  jason  miller   42    m    4.0    25.0     seoul
b    NaN     NaN   25  NaN    NaN     NaN   Incheon
c   tina     all   78    f    NaN     NaN     Pusan
d   jake   miler   41    m    2.0    62.0   Gwangju
e    amy  coozer   23    f    3.0    70.0  Daejeoun

In [254]:
df.dropna(axis=1)

age      addr
a   42     seoul
b   25   Incheon
c   78     Pusan
d   41   Gwangju
e   23  Daejeoun

In [255]:
# 37

In [256]:
df.fillna(0)

fn      ln  age sex  prets  postts      addr
a  jason  miller   42   m    4.0    25.0     seoul
b      0       0   25   0    0.0     0.0   Incheon
c   tina     all   78   f    0.0     0.0     Pusan
d   jake   miler   41   m    2.0    62.0   Gwangju
e    amy  coozer   23   f    3.0    70.0  Daejeoun

In [257]:
# 38

In [258]:
df[df.ln == 'all']

fn   ln  age sex  prets  postts   addr
c  tina  all   78   f    NaN     NaN  Pusan

In [259]:
# 39

In [260]:
df[df.postts >= 50].ln

d     miler
e    coozer
Name: ln, dtype: object

In [261]:
# 40 

In [262]:
df.dropna(axis=0)

fn      ln  age sex  prets  postts      addr
a  jason  miller   42   m    4.0    25.0     seoul
d   jake   miler   41   m    2.0    62.0   Gwangju
e    amy  coozer   23   f    3.0    70.0  Daejeoun

In [263]:
# 41

In [264]:
df[df.sex == 'f']

fn      ln  age sex  prets  postts      addr
c  tina     all   78   f    NaN     NaN     Pusan
e   amy  coozer   23   f    3.0    70.0  Daejeoun

In [265]:
# 42

In [266]:
df.loc[['a','c'], [ 'fn', 'ln']]

fn      ln
a  jason  miller
c   tina     all

In [267]:
# 43 

In [268]:
df.to_csv('test_df.csv')

In [269]:
# 44

In [270]:
df1 = df.dropna()
df1['ln'] = df1['ln'].apply(lambda x : x.upper())
df1

<ipython-input-270-9bf9a7871467>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['ln'] = df1['ln'].apply(lambda x : x.upper())


fn      ln  age sex  prets  postts      addr
a  jason  MILLER   42   m    4.0    25.0     seoul
d   jake   MILER   41   m    2.0    62.0   Gwangju
e    amy  COOZER   23   f    3.0    70.0  Daejeoun

In [271]:
df1 = df.fillna('nan')
df1['ln'] = df1['ln'].apply(lambda x : x.upper())
df1

fn      ln  age  sex prets postts      addr
a  jason  MILLER   42    m     4     25     seoul
b    nan     NAN   25  nan   nan    nan   Incheon
c   tina     ALL   78    f   nan    nan     Pusan
d   jake   MILER   41    m     2     62   Gwangju
e    amy  COOZER   23    f     3     70  Daejeoun

In [277]:
df.ln

a    miller
b       NaN
c       all
d     miler
e    coozer
Name: ln, dtype: object

In [280]:
temp = []
for i in df.ln:
#     print(i)
    if str(i) == 'nan':
        temp.append(i)
    else:
        temp.append(i.upper())
temp

['MILLER', nan, 'ALL', 'MILER', 'COOZER']

In [ ]:
# 45

In [158]:
df.sort_values('age', ascending=False)

fn      ln  age  sex  prets  postts      addr
c   tina     all   78    f    NaN     NaN     Pusan
a  jason  miller   42    m    4.0    25.0     seoul
d   jake   miler   41    m    2.0    62.0   Gwangju
b    NaN     NaN   25  NaN    NaN     NaN   Incheon
e    amy  coozer   23    f    3.0    70.0  Daejeoun

In [159]:
# 46

In [160]:
df['age'] = df.age.apply(lambda x: x-1)
df

fn      ln  age  sex  prets  postts      addr
a  jason  miller   41    m    4.0    25.0     seoul
b    NaN     NaN   24  NaN    NaN     NaN   Incheon
c   tina     all   77    f    NaN     NaN     Pusan
d   jake   miler   40    m    2.0    62.0   Gwangju
e    amy  coozer   22    f    3.0    70.0  Daejeoun

In [161]:
# 47

In [163]:
df.sex.value_counts()

m    2
f    2
Name: sex, dtype: int64

In [164]:
# 48 ‘pretestscore’,‘posttestscore’열을 row의 값으로 전환하고 나머지 column은 고정하시오.

In [165]:
df

fn      ln  age  sex  prets  postts      addr
a  jason  miller   41    m    4.0    25.0     seoul
b    NaN     NaN   24  NaN    NaN     NaN   Incheon
c   tina     all   77    f    NaN     NaN     Pusan
d   jake   miler   40    m    2.0    62.0   Gwangju
e    amy  coozer   22    f    3.0    70.0  Daejeoun

In [281]:
df

fn      ln  age  sex  prets  postts      addr
a  jason  miller   42    m    4.0    25.0     seoul
b    NaN     NaN   25  NaN    NaN     NaN   Incheon
c   tina     all   78    f    NaN     NaN     Pusan
d   jake   miler   41    m    2.0    62.0   Gwangju
e    amy  coozer   23    f    3.0    70.0  Daejeoun

In [169]:
# 49

In [170]:
df['age'] = df.age.astype('int')
# df['age'] = pd.to_numeric(df['age'])

In [171]:
# 50

In [172]:
data = {'Team':['Riders','Riders','Devils','Devils','Kings','Giant',\
               'Kings','Kings','Riders','Royals','Royals','Riders'],\
       'Rank':[1,2,2,3,3,4,1,1,2,4,1,2],\
       'Year':[2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],\
       'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(data)
df

Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Giant     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [173]:
# 51

In [174]:
df.groupby('Team')['Points'].sum()

Team
Devils    1536
Giant      812
Kings     2285
Riders    3049
Royals    1505
Name: Points, dtype: int64

In [175]:
# 52

In [176]:
df.groupby(['Team','Year'])['Points'].sum()

Team    Year
Devils  2014    863
        2015    673
Giant   2015    812
Kings   2014    741
        2016    756
        2017    788
Riders  2014    876
        2015    789
        2016    694
        2017    690
Royals  2014    701
        2015    804
Name: Points, dtype: int64

In [177]:
# 53

In [180]:
df[df.Team == 'Devils']['Points'].mean()

768.0

In [181]:
# 54

In [183]:
df.groupby('Team').Year.count()

Team
Devils    2
Giant     1
Kings     3
Riders    4
Royals    2
Name: Year, dtype: int64

In [184]:
# 55

In [186]:
df.groupby('Team').Rank.min()

Team
Devils    2
Giant     4
Kings     1
Riders    1
Royals    1
Name: Rank, dtype: int64

In [187]:
# 56

In [193]:
grouped = df.groupby("Team")
grouped.agg([sum, np.mean, np.std])

Rank                      Year                        Points  \
        sum      mean       std   sum         mean       std    sum   
Team                                                                  
Devils    5  2.500000  0.707107  4029  2014.500000  0.707107   1536   
Giant     4  4.000000       NaN  2015  2015.000000       NaN    812   
Kings     5  1.666667  1.154701  6047  2015.666667  1.527525   2285   
Riders    7  1.750000  0.500000  8062  2015.500000  1.290994   3049   
Royals    5  2.500000  2.121320  4029  2014.500000  0.707107   1505   

                                
              mean         std  
Team                            
Devils  768.000000  134.350288  
Giant   812.000000         NaN  
Kings   761.666667   24.006943  
Riders  762.250000   88.567771  
Royals  752.500000   72.831998

In [194]:
# 57

In [195]:
raw_data = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_score': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
df1 = pd.DataFrame(raw_data)

raw_data = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}
df2 = pd.DataFrame(raw_data)


In [197]:
df1.head()

subject_id  test_score
0          1          51
1          2          15
2          3          15
3          4          61
4          5          16

In [198]:
df2.head()

subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

In [199]:
# 57

In [202]:
pd.merge(df1, df2, on='subject_id', how='inner')

subject_id  test_score first_name last_name
0          4          61      Billy    Bonder
1          5          16      Brian     Black
2          7          14      Bryce     Brice
3          8          15      Betty    Btisan

In [203]:
pd.merge(df1, df2, on='subject_id', how='right')

subject_id  test_score first_name last_name
0          4        61.0      Billy    Bonder
1          5        16.0      Brian     Black
2          7        14.0      Bryce     Brice
3          8        15.0      Betty    Btisan
4          6         NaN       Bran   Balwner

In [204]:
pd.merge(df1, df2, on='subject_id', how = 'left')

subject_id  test_score first_name last_name
0          1          51        NaN       NaN
1          2          15        NaN       NaN
2          3          15        NaN       NaN
3          4          61      Billy    Bonder
4          5          16      Brian     Black
5          7          14      Bryce     Brice
6          8          15      Betty    Btisan
7          9           1        NaN       NaN
8         10          61        NaN       NaN
9         11          16        NaN       NaN

In [205]:
pd.merge(df1, df2, on='subject_id', how='outer')

subject_id  test_score first_name last_name
0           1        51.0        NaN       NaN
1           2        15.0        NaN       NaN
2           3        15.0        NaN       NaN
3           4        61.0      Billy    Bonder
4           5        16.0      Brian     Black
5           7        14.0      Bryce     Brice
6           8        15.0      Betty    Btisan
7           9         1.0        NaN       NaN
8          10        61.0        NaN       NaN
9          11        16.0        NaN       NaN
10          6         NaN       Bran   Balwner

In [206]:
# 58

In [207]:
pd.concat([df1, df2], axis=1)

subject_id  test_score subject_id first_name last_name
0          1          51          4      Billy    Bonder
1          2          15          5      Brian     Black
2          3          15          6       Bran   Balwner
3          4          61          7      Bryce     Brice
4          5          16          8      Betty    Btisan
5          7          14        NaN        NaN       NaN
6          8          15        NaN        NaN       NaN
7          9           1        NaN        NaN       NaN
8         10          61        NaN        NaN       NaN
9         11          16        NaN        NaN       NaN

In [208]:
pd.concat([df1, df2], axis=0)

subject_id  test_score first_name last_name
0          1        51.0        NaN       NaN
1          2        15.0        NaN       NaN
2          3        15.0        NaN       NaN
3          4        61.0        NaN       NaN
4          5        16.0        NaN       NaN
5          7        14.0        NaN       NaN
6          8        15.0        NaN       NaN
7          9         1.0        NaN       NaN
8         10        61.0        NaN       NaN
9         11        16.0        NaN       NaN
0          4         NaN      Billy    Bonder
1          5         NaN      Brian     Black
2          6         NaN       Bran   Balwner
3          7         NaN      Bryce     Brice
4          8         NaN      Betty    Btisan